version: "3.8"

services:
  account-management-center:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: account-management-center
    ports:
      - "8011:8000"
    volumes:
      - .:/app  # 可选：挂载代码目录以便热更新或调试
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped